---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - debug: var="{{ host }}"
  - name: Junos JSNAPy
    junos_snapy:
      device: "{{ host }}"
      username: denali
      passwd: denali11
      tests:
         - tests_lab_state.yml
    register: test_result
  - debug: var=test_result
