---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - debug: var="{{ host }}"
  - name: Telstra Snappy
    telstra_snappy:
      device: "{{ host }}"
      username: denali
      passwd: denali11
      platform: junos
      tests:
         - tests_lab_state.yml
    register: test_result
  - debug: var=test_result
