---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - debug: var="{{ host }}"
  - name: Telstra Snappy
    telstra_snappy:
      device: "{{ host }}"
      username: cisco
      passwd: cisco
      platform: junos
      tests:
         - test123.yml
