---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Download testcases from GIT
    git: repo="https://github.com/denalitt/testcases.git"
         dest="/tmp/testcases"
         force=yes

  - name: Junos JSNAPy Post Check
    junos_jsnapy:
      host: "{{ item[0] }}"
      user: denali
      passwd: denali11
      action: snap_post
      dir: /tmp/testcases
      test_files:
         - "{{ item[1] }}"
    with_nested:
         - "{{ devices }}"
         - "{{ op  + config + user_defined }}"
  - name: Junos JSNAPy Compare PRE and POST 
    junos_jsnapy:
      host: "{{ item[0] }}"
      user: denali
      passwd: denali11
      action: check
      dir: /tmp/testcases
      test_files:
         - "{{ item[1] }}"
    with_nested:
         - "{{ devices }}"
         - "{{ op  + config + user_defined }}"
    register: check_result
  - debug: var=check_result['results']
