---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Download testcases from GIT
    git: repo="https://github.com/denalitt/testcases.git"
         dest="/tmp/testcases"
         force=yes

  - name: Junos JSNAPy
    junos_jsnapy:
      host: "{{ item }}"
      user: denali
      passwd: denali11
      action: snapcheck
      dir: /tmp/testcases
      test_files:
         - "op/{{ op }}"
         - "config/{{ config }}"
    register: test_result
    with_items:
         - "{{ hosts }}"
  - debug: var=test_result.results
